### ISSUE TITLE
2.1.0 release - undefined reference to `MenuSystem::select()'

### ISSUE THREAD

**Issue by hestenet** [jonblack/arduino-menusystem#17]
After recompiling my code following the 2.1.0 release I'm seeing a large number of 
`undefined reference to `MenuSystem::select()'` errors.''

I'm not sure why... could it have something to do with this change:
` MenuSystem.h line 82:   - void select(boolean return_to_root=true);`

select() no longer has a return_to_root behavior?

**Comment by jonblack** [comment]
I removed `return_to_root` and replaced it with a separate function `reset`. In retrospect perhaps that wasn't the best idea. I was looking at it from the use case where a single menu item causes the reset, but some people may want to reset after every call to `select`. This is possible with `reset` but would require a call to reset in all callbacks, which is a bit cumbersome.

I'll reintroduce the option, though it'll be renamed: `MenuComponent* select(reset=false)`.

**Comment by hestenet** [comment]
That sounds good! I'll be happy to test it out.

**Comment by jonblack** [comment]
This is now fixed in 2.1.1.

**Comment by hestenet** [comment]
Thank you - my sketch from 2.0.2 now compiles on 2.1.1 without errors.
